---
name: Bug report
description: Create a report to help us improve
labels:
  - triage

body:
  - type: markdown
    attributes:
      value: |
        Thank you for reporting a bug problem with Snowsky Echo Mini Toolbox.

        Pleas ensure you have the latest version of Snowsky Echo Mini Toolbox installed.
        You can find the latest version in the [releases page](https://github.com/silent-sphinx/snowsky-echo-mini-toolbox/releases).
        If the issue still occurs, please report the issue.

        If your bug report is about a incompatible file not marked as incompatible by the program, please submit a file incompatibility report.

  - type: input
    id: version
    attributes:
      label: Snowsky Echo Mini Toolbox version
      description: Enter the complete Snowsky Echo Mini Toolbox version where the issue occurs, this can be found in the top-left corner next to the title, or in the bottom right corner for versions > 2.0.0.
      placeholder: v2.0.0
    validations:
      required: true

  - type: dropdown
    id: operating-system
    attributes:
      label: Operating System
      description: Select the operating system of the device where the issue occurs.
      options:
        - Windows (x64)
        - Windows (arm64)
        - Linux (x64)
        - Linux (arm64)
        - MacOS (x64)
        - MacOS (arm64)
        - Other
    validations:
      required: true

  - type: dropdown
    id: feature-affected
    attributes:
      label: Feature Affected
      description: Select the feature affected by the issue.
      options:
        - Device information
        - Music Browser
        - Music Compatibility
        - File Rename
        - Backup & Restore
        - Lyrics Manager
        - Album Art Manager
        - File Cleanup
        - Workflows
        - Other
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Describe the bug
      description: Clearly describe what is happening and its impact.
      placeholder: Describe the problem you encountered.
    validations:
      required: true

  - type: textarea
    id: reproduction-steps
    attributes:
      label: Steps to reproduce
      description: Provide the sequence of steps that consistently reproduces the issue.
      placeholder: |
        1. Go to ...
        2. Click on ...
        3. Enter ...
        4. Observe ...
    validations:
      required: true

  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected behavior
      description: Describe what you expected to happen.
    validations:
      required: true

  - type: textarea
    id: additional-context
    attributes:
      label: Additional context
      description: Include any other details that may help diagnose the issue.

  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots or screen recordings
      description: Drag and drop any relevant screenshots or recordings here.

  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: Paste relevant, redacted log output. Remove any sensitive information.
      render: shell