---
name: Incompatible Music File Report
description: Create a report to help us improve incompatible file detection
labels:
  - triage

body:
  - type: markdown
    attributes:
      value: |
        Thank you for reporting a bug problem with Snowsky Echo Mini Toolbox.

        Pleas ensure you have the latest version of Snowsky Echo Mini Toolbox installed.
        You can find the latest version in the [releases page](https://github.com/silent-sphinx/snowsky-echo-mini-toolbox/releases).
        If the issue still occurs, please report the issue.

  - type: input
    id: version
    attributes:
      label: Snowsky Echo Mini Toolbox version
      description: Enter the complete Snowsky Echo Mini Toolbox version where the issue occurs, this can be found in the top-left corner next to the title, or in the bottom right corner for versions > 2.0.0.
      placeholder: v2.0.0
    validations:
      required: true

  - type: dropdown
    id: operating-system
    attributes:
      label: Operating System
      description: Select the operating system of the device where the issue occurs.
      options:
        - Windows (x64)
        - Windows (arm64)
        - Linux (x64)
        - Linux (arm64)
        - MacOS (x64)
        - MacOS (arm64)
        - Other
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Describe the bug
      description: Clearly describe what is happening and its impact.
      placeholder: Describe the problem you encountered.
    validations:
      required: true

  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots or screen recordings
      description: Drag and drop any relevant screenshots or recordings here.

  - type: textarea
    id: debug-message
    attributes:
      label: Audio File Debug Message
      description: Locate your music file using the 'File Browser' tab, right-click on the file and select 'debug', paste the output of the launched window here.

  - type: textarea
      id: music-file
      attributes:
        label: Incompatible Music File
        description: Drag and drop any incompatible audio files, or provide a link to a cloud-storage service like Google Drive.

  - type: textarea
    id: additional-context
    attributes:
      label: Additional context
      description: Include any other details that may help diagnose the issue.